### ISSUE TITLE
[Proposal]: Veel waarde uit weinig logging

### ISSUE THREAD

**Issue by LucaScorpion** [nimma-codes/talks#11]
### Talk title

Veel waarde uit weinig logging

### The Abstract

Logging is in veel projecten een ondergeschoven kindje, wat - als het al gebruikt wordt - voornamelijk als debugging-tool ingezet wordt. Dit is zonde, want er valt extreem veel waarde te behalen uit relatief simpele logging, voor developers, maar ook voor de business. Ik wil laten zien hoe je goed gestructureerd kan loggen om uit een enkele message verschillende interessante metrics te extraheren.

### The duration of your talk

30 minuten, kan mogelijk ook als lightning talk

### Tell us more about yourself as a speaker

Ik ben Luca, een freelance full-stack developer ~en tech lead bij Infi, waar ik inmiddels ruim 3 jaar werk.~ Bij Infi heb ik veel verschillende projecten gedaan, en daar allerlei ervaringen opgepikt. Ik hou ervan om nieuwe dingen te leren en uit te proberen, en in mijn vrije tijd ben ik ook regelmatig bezig met allerlei hobbyprojecten.

### format

Regular talk

**Comment by jeroenhuinink** [comment]
This talk was presented as a lightning talk on 2024-11-26: https://www.meetup.com/nimma-codes-meetup-group/events/303824017.

@LucaScorpion wil je hem nog open laten staan voor een full-length talk?

**Comment by LucaScorpion** [comment]
Voor nu vind ik hem even goed geweest, het blijft interessant maar ik ben er atm minder in mijn day to day mee bezig, dus ik zal hem sluiten! Wie weet in de toekomst een revised versie :)
