### ISSUE TITLE
[Proposal]: Hoeveel abstracties maken/gebruiken we eigenlijk in onze software?

### ISSUE THREAD

**Issue by WilbertAtIctGroup** [nimma-codes/talks#13]
### Talk title

It's abstractions all the way down

### The Abstract

Een jaartje geleden heb ik een project gedaan waar met behulp van een stralingsdetector de radioactiviteit van medische isotopen werd gemeten. 

Na de bouw realiseerde ik me hoeveel abstracties er eigenlijk in de software zijn gemaakt om vanaf het begin (de stralingsmeter) te komen tot het eind (een waarde-oordeel of de activiteit binnen verwachting is). 

Het lijkt mij interessant om al deze abstracties eens uit te werken en toe lichten en zo een beeld te geven hoe we abstracties in onze software gebruiken. 

Een beetje een mix tussen een presentatie van een project en een aantal lessons learned.

### The duration of your talk

Moet het nog uitwerken maar toch zeker 45-60 minuten

### Tell us more about yourself as a speaker

Moet dat nog? Wilbert van Dolleweerd, software architectect bij ICT Group en vaste bezoeker van Nimma.codes. Ik hou me vooral bezig met custom projecten voor klanten met een raakvlak met industriele automatisering.

### format

Regular talk

**Comment by dotkarl** [comment]
Ik vind dit een leuke, ik denk dat het komt door mijn filosofieachtergrond: het staat stil bij iets wat we de hele dag door haast gedachteloos doen.

Klein kritiekpuntje wel (als ik zo vrij mag zijn), de eigenlijke vraag is denk ik niet: hoeveel abstracties gebruiken we, maar: waarom gebruiken we? -- En er zijn natuurlijk een heleboel redenen voor het introduceren van een abstractie, dat zal een reden zijn waarom het er zoveel worden op den duur. Maar de ene abstractie is de andere niet, en daar zit denk ik dus de interessante vraag verstopt.

**Comment by WilbertOnGithub** [comment]
Hoi @dotkarl , kritiek is altijd welkom. Het idee was inderdaad om aan te geven waarom we een abstractie introduceren en wat dit aan voordelen oplevert. 

Dat neemt niet weg dat je soms niet volledig van een abstractie kan uitgaan. Soms is het nodig om de waarheid achter het gordijn te kunnen zien. Zie ook [leaky abstractions](https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/)

**Comment by WilbertOnGithub** [comment]
Overigens zou ik een zeer kleine versie van deze talk wel als een lightning sessie kunnen doen. Vooral door 1 abstractie uit te werken met als achterliggend idee dat het belangrijk voor je is als ontwikkelaar om de domeinkennis eigen te maken.

**Comment by jeroenhuinink** [comment]
This talk was presented as a lightning talk on 2024-11-26: https://www.meetup.com/nimma-codes-meetup-group/events/303824017.

@WilbertOnGithub wil je deze nog open laten staan voor een full-length talk?

**Comment by WilbertOnGithub** [comment]
@jeroenhuinink Nee, ik denk dat dit wel even voldoende was. Ik heb nog wel ideetjes voor andere talks.
