### ISSUE TITLE
[Proposal]: AI in je IDE: Mijn ervaring met Cursor.ai

### ISSUE THREAD

**Issue by bramdoppen** [nimma-codes/talks#15]
### Talk title

AI in je IDE: Mijn ervaring met Cursor.ai

### The Abstract

In deze talk deel ik mijn recente ervaring met Cursor.ai, een AI-geïntegreerde IDE. Ik heb binnen no-time een simpele website kunnen bouwen, maar liep tegen het probleem aan dat ik het overzicht over de gegenereerde code kwijtraakte. Tijdens de talk bespreek ik de voordelen van AI in development, maar ook de uitdagingen die daarbij komen kijken, zoals controle en begrip van de gegenereerde code. We staan stil bij de impact die AI-tools kunnen hebben op het werk van developers, en ik bied praktische inzichten in hoe we als developers deze tools kunnen omarmen zonder de controle te verliezen. Oh, en ik zal natuurlijk een demo geven.

### The duration of your talk

15 minuten

### Tell us more about yourself as a speaker

Bram is lead front-end developer bij Linku, met een passie voor het creëren van toffe gebruikerservaringen en het oplossen van complexe front-end uitdagingen. Met een scherp oog voor detail en een creatieve geest, streeft Bram er altijd naar om hoogwaardige en gebruiksvriendelijke webapplicaties te ontwikkelen.

### format

Interactive format like dojo or otherwise

**Comment by jeroenhuinink** [comment]
This talk was presented as a lightning talk on 2024-11-26: https://www.meetup.com/nimma-codes-meetup-group/events/303824017
