### ISSUE TITLE
[Proposal]: De filosofische geschiedenis van een ontwerpkeuze

### ISSUE THREAD

**Issue by dotkarl** [nimma-codes/talks#16]
### Talk title

De filosofische geschiedenis van een ontwerpkeuze

### The Abstract

Softwareontwikkelaars schrijven niet slechts code, ze scheppen een model van de werkelijkheid. Wat dat betreft staan ze in een lange filosofische traditie. Oftewel: wat kunnen Plato en Wittgenstein ons leren over het modelleren van een (on)geverifieerd e-mailadres?

### The duration of your talk

Lightning talk

### Tell us more about yourself as a speaker

Karl van Heijster is softwareontwikkelaar maar studeerde filosofie. Hij is geïnteresseerd in software craftsmanship, test-driven development en domain-driven design. Op [www.karlvanheijster.com](http://www.karlvanheijster.com/) houdt hij wekelijks zijn observaties over de softwareontwikkelpraktijk bij.

### format

Regular talk

**Comment by jeroenhuinink** [comment]
This talk was presented as a lightning talk on 2024-11-26: https://www.meetup.com/nimma-codes-meetup-group/events/303824017
