### ISSUE TITLE
[Proposal]: De edele kunst van het pull request

### ISSUE THREAD

**Issue by dotkarl** [nimma-codes/talks#2]
### Talk title

De edele kunst van het pull request

### The Abstract

Veel ontwikkelaars zien code reviews als een hinderlijke onderbreking van hun werkzaamheden. Maar het goed kunnen beoordelen van een codewijziging is essentieel om de kwaliteit van een codebase op peil te houden. Gelukkig hoeft dit proces niet pijnlijk te zijn. Aan het eind van deze sessie weet je welke vragen je moet stellen voor een geslaagde code review - en hoe je deze informatie zo effectief mogelijk overbrengt in je PR.

### The duration of your talk

45 min.

### Tell us more about yourself as a speaker

Karl van Heijster is softwareontwikkelaar bij Stichting Cito in Arnhem. Hij is geïnteresseerd in software craftmanship, agile en test-driven development. Op [www.karlvanheijster.com](http://www.karlvanheijster.com/) houdt hij wekelijks zijn observaties over de softwareontwikkelpraktijk bij.

### format

Regular talk

**Comment by bramdoppen** [comment]
@dotkarl Thanks voor je proposal hier op Github Issues! Pull requests zijn in mijn werk ook een dagelijks terugkerend onderdeel, ben benieuwd.
