### ISSUE TITLE
[Proposal]: The philosophy of ubiquitous language

### ISSUE THREAD

**Issue by dotkarl** [nimma-codes/talks#3]
### Talk title

The philosophy of ubiquitous language

### The Abstract

Domain-Driven Design vraagt ons om de code te schrijven in de taal van de business. Dat betekent dat de manier waarop we onze code vormgeven, op een fundamenteel niveau afhankelijk wordt van onze vooronderstellingen over taal. In deze talk analyseren we, aan de hand van de filosofie van Ludwig Wittgenstein (1889 - 1951), welke noties van betekenis er ten grondslag liggen aan verschillende modelleeroplossingen.

### The duration of your talk

60 min.

### Tell us more about yourself as a speaker

Karl van Heijster is softwareontwikkelaar bij Stichting Cito in Arnhem. Hij is geïnteresseerd in software craftmanship, agile en test-driven development. Op [www.karlvanheijster.com](http://www.karlvanheijster.com/) houdt hij wekelijks zijn observaties over de softwareontwikkelpraktijk bij.

### format

Regular talk

**Comment by bramdoppen** [comment]
Thanks voor je submission via Github Issues! Als ik 'm naast je andere talk #2 leg lijkt deze abstracter dan die andere. Stof tot nadenken! :)
