### ISSUE TITLE
[Proposal]: Product management voor developers

### ISSUE THREAD

**Issue by FubFubFub** [nimma-codes/talks#4]
### Talk title

Product management voor developers

### The Abstract

Als je een product maakt, dan heb je altijd met product management te maken, ook als je niet een persoon hebt die dat in hun functie-titel heeft. Dat betekent dat anderen de activiteiten van product management doen, en als je geluk hebt, dan gebeurt dat op een goede manier. In deze talk vertel ik een paar dingen over product management waarmee je als developer kan helpen om de juiste kant op te sturen -- en het zo wat minder van geluk af te laten hangen.
Onderwerpen:
- Wat is product management (en wanneer heb je eigenlijk een product)?
- Hoe doe je product management (goed)?
- Veel voorkomende valkuilen

### The duration of your talk

30 of 45 mins

### Tell us more about yourself as a speaker

Hein landde in product management na een gevarieerde carriere in wetenschap, software development en consultancy. Hij heeft veel ervaring in het managen van saaie business software, onder andere voor document compositie en enterprise content management. Op dit moment is hij verantwoordelijk voor Alfresco Content Services, een open source ECM systeem. Zijn favoriete vraag is "Waarom?"

### format

Regular talk

**Comment by matthijsl** [comment]
Bedankt voor je submission via Github Issues! :)
