### ISSUE TITLE
[Proposal]: Mutation Testing

### ISSUE THREAD

**Issue by jeroenhuinink** [nimma-codes/talks#6]
### Talk title

Onder de motor kap bij mutation testen

### The Abstract

De Latijnse uitdrukking “Quis custodiet ipsos custodes?” (Wie bewaakt de bewaker) is ook van toepassing op tests. Hoe stel je vast dat je tests het goede testen? Welke maat kun je gebruiken voor de kwaliteit van de tests? Een veelgebruikte maat is coverage: het aantal regels code die geraakt worden in de uitvoering van een test. Veel teams gebruiken een doelpercentage (80% code coverage) als maat voor het bepalen van de kwaliteit van de tests. Maar je kunt relatief eenvoudig een hoge code coverage bereiken zonder dat je daadwerkelijk goede tests schrijft. Gelukkig zijn er ook andere manieren om de kwaliteit van je tests vast te stellen.

In deze talk wil ik iets vertellen over mutation testing: wat is het en wat kan het voor je doen en ook even in de code duiken van mutation testing tools om te zien hoe ze dit voor elkaar krijgen.

### The duration of your talk

45 min

### Tell us more about yourself as a speaker

Vanuit mijn studie informatica ben ik begonnen bij Aia Software in Nijmegen als implementatie consultant. Daar ben ik 20 jaar gebleven en heen en weer gegaan tussen technische en management/commerciele functie. Mijn laatste rol daar was (na een overname door een Amerikaans bedrijf) "Senior Vice President Product Marketing", dat was een heel visite kaartje vol.

Inmiddels werk ik bijna 5 jaar bij Infi waar ik nu directeur ben van Infi Nijmegen. In mijn werk bij Aia heb ik ook wel periodes geprogrammeerd maar ik heb nog nooit zoveel code getypt als de afgelopen 5 jaar bij Infi.  

### format

Regular talk

**Comment by matthijsl** [comment]
Bedankt voor de talk proposal @jeroenhuinink ! :smile:

**Comment by jeroenhuinink** [comment]
This talk was presented at the lightning talks session on 2024-03-26: https://www.meetup.com/nimma-codes-meetup-group/events/298952291
