### ISSUE TITLE
[Proposal]: Exceptional error handing in Typescript

### ISSUE THREAD

**Issue by everweij** [nimma-codes/talks#8]
### Talk title

Exceptional error handing in Typescript

### The Abstract

I’ve noticed that developers often have different styles when it comes to dealing with things that might go 💥  in a running application - those pesky exceptions! While some projects boast a well-defined error-handling strategy, I've frequently witnessed developers struggle with effectively managing errors: What should you do with that scary thing you just caught in your try-catch block? Do you even catch exceptions at all? How should you know what can go wrong in the first place? 

Let's delve into the realm of errors and exceptions, seeking to master these notorious troublemakers. In this talk, we'll start with a brief overview of error-handling features in JS/TS. We'll explore what you can do once you have caught an exception, examining different strategies, patterns, and best practices. Lastly, we'll look at the drawbacks of the discussed approaches, explore an emerging alternative gaining traction in other languages, and consider how TypeScript can elevate this paradigm even further.

_Note: although the examples will be in Typescript, the concepts and examples in this talk will most likely translate easily to other languages as well._

### The duration of your talk

45 min

### Tell us more about yourself as a speaker

Erik is a passionate and versatile software engineer who currently works as a consultant for Xebia. He loves to read, write, and talk about software craftsmanship in general. When he’s not working on one of his side projects, he likes to grab his bike for a ride or grab his Fender Stratocaster to play some tunes.

### format

Regular talk

**Comment by smdehaas** [comment]
Interessant onderwerp Erik! 👍

**Comment by bramdoppen** [comment]
Gegeven op 25 juni. Nogmaals dank @everweij . Ik close deze.
